name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        
        MYSQLHOST: ${{ secrets.MYSQLHOST }}
        MYSQLPORT: ${{ secrets.MYSQLPORT }}
        MYSQLUSER: ${{ secrets.MYSQLUSER }}
        MYSQLPASSWORD: ${{ secrets.MYSQLPASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

        EXCHANGE_TOKEN: ${{ secrets.EXCHANGE_TOKEN }}
        WEATHER_TOKEN: ${{ secrets.WEATHER_TOKEN }}
      run: pytest -v
