name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # test:
  #   needs: lint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python 3.11
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install pytest-mock

  #     - name: Run tests
  #       env:
  #         API_TOKEN: ${{ secrets.API_TOKEN }}
        
  #         MYSQLHOST: ${{ secrets.MYSQLHOST }}
  #         MYSQLPORT: ${{ secrets.MYSQLPORT }}
  #         MYSQLUSER: ${{ secrets.MYSQLUSER }}
  #         MYSQLPASSWORD: ${{ secrets.MYSQLPASSWORD }}
  #         MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  
  #         EXCHANGE_TOKEN: ${{ secrets.EXCHANGE_TOKEN }}
  #         WEATHER_TOKEN: ${{ secrets.WEATHER_TOKEN }}
        
  #       run: pytest -v

  deploy:
    needs: lint
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/xenocode/casinoBot
            git pull
            echo "TMG5Pk8Y" | sudo -S systemctl restart casinoBot
            echo "done7"